### ISSUE TITLE
libtexture_share_gl_client.so fails to load with undefined symbol: glad_glDeleteTextures

### ISSUE THREAD

**Issue by SunsetTech** [DigitOtter/texture-share-vk#1]
installed from the AUR, used through obs-plugin-texture-share-vk. glad was installed on system at time of build

**Comment by DigitOtter** [comment]
I just updated the PKGBUILD of `texture-share-vk-git`, let me know if it works.

**Comment by SunsetTech** [comment]
Yes it is working now, thank you
